const agents=[
{id:1,group:'Strategy & Workforce',icon:'🧭',name:'HR Strategist',thai:'นักกลยุทธ์ทรัพยากรบุคคล',eq:'HR Business Partner / HR Manager',desc:'เชื่อมกลยุทธ์ธุรกิจกับ People Strategy, HR Roadmap และการจัดลำดับโครงการ',when:'เมื่อธุรกิจกำลังเปลี่ยนโครงสร้างหรือกำหนดเป้าหมายใหม่',prompt:'วิเคราะห์เป้าหมายธุรกิจและจัดทำ HR Roadmap 90 วัน พร้อม 5 เรื่องที่ควรทำก่อน'},
{id:2,group:'Strategy & Workforce',icon:'📐',name:'Workforce Planner',thai:'นักวางแผนอัตรากำลัง',eq:'Workforce Planning / HRBP',desc:'วิเคราะห์ Headcount, Capacity, Shift, Productivity และ Manpower Budget',when:'เมื่อกำลังคนไม่พอกับ workload หรือกำลังจะเพิ่ม/ลดทีม',prompt:'วิเคราะห์กำลังคนจากยอดงานและตารางกะ แล้วเสนอ Manpower Plan รายเดือน'},
{id:3,group:'Strategy & Workforce',icon:'🎯',name:'Talent Acquisition AI',thai:'นักสรรหาอัจฉริยะ',eq:'Talent Acquisition Specialist',desc:'แตก JD, sourcing strategy, screening rubric และ interview guide',when:'เมื่อเปิดตำแหน่งใหม่หรือมีผู้สมัครจำนวนมาก',prompt:'สร้างเกณฑ์คัดกรองผู้สมัครจาก JD นี้ พร้อมคำถามสัมภาษณ์แบบมี scoring'},
{id:4,group:'Employee Lifecycle',icon:'🚀',name:'Onboarding Manager',thai:'ผู้จัดการ Onboarding',eq:'HR Officer / People Operations',desc:'สร้าง checklist รับพนักงานใหม่ ติดตาม probation และ handover',when:'ก่อนพนักงานเริ่มงานและก่อนครบทดลองงาน',prompt:'สร้าง Onboarding plan 30-60-90 วันสำหรับตำแหน่งนี้ พร้อม owner และ deadline'},
{id:5,group:'Employee Lifecycle',icon:'⏱',name:'Attendance Analyst',thai:'นักวิเคราะห์เวลาทำงาน',eq:'HR Operations / Time Attendance',desc:'วิเคราะห์เวลาเข้า-ออก ลา มาสาย ขาดงาน OT และรูปแบบผิดปกติ',when:'เมื่อมีข้อมูลเวลาและต้องการหา anomaly',prompt:'วิเคราะห์ข้อมูล Attendance เดือนนี้ หาคน/ทีมที่ผิดปกติและสาเหตุที่ควรตรวจเพิ่ม'},
{id:6,group:'Employee Lifecycle',icon:'💰',name:'Payroll Specialist',thai:'ผู้เชี่ยวชาญ Payroll',eq:'Payroll Specialist',desc:'ตรวจความครบถ้วนของ input เงินเดือน ลา OT หัก และ validation rules',when:'ก่อนปิดรอบเงินเดือน',prompt:'ตรวจ Payroll input ตาม checklist และระบุรายการที่ต้องให้คนตรวจยืนยัน'},
{id:7,group:'Employee Lifecycle',icon:'⚖',name:'Compensation Analyst',thai:'นักวิเคราะห์ค่าตอบแทน',eq:'Compensation & Benefits',desc:'วิเคราะห์ salary structure, incentive, internal equity และ benchmark',when:'ปรับเงินเดือน ตั้ง incentive หรือทบทวนโครงสร้าง',prompt:'วิเคราะห์โครงสร้างค่าตอบแทนจากข้อมูลนี้และระบุจุดเสี่ยงด้าน internal equity'},
{id:8,group:'Employee Lifecycle',icon:'🎁',name:'Benefits Specialist',thai:'ผู้ดูแลสวัสดิการ',eq:'Benefits Specialist',desc:'จัดการสิทธิ สวัสดิการ FAQ และตรวจเงื่อนไขการเบิก',when:'พนักงานถามสิทธิหรือ HR ต้องสื่อสาร benefit ใหม่',prompt:'สรุปสิทธิประโยชน์นี้เป็น FAQ สำหรับพนักงาน พร้อมกรณีที่ต้องส่งต่อ HR'},
{id:9,group:'Employee Relations & Compliance',icon:'🤝',name:'Employee Relations Advisor',thai:'ที่ปรึกษาพนักงานสัมพันธ์',eq:'Employee Relations Specialist',desc:'จัดโครงสร้างข้อร้องเรียน สรุป evidence และเตรียมทางเลือกในการจัดการ case',when:'มี complaint, conflict หรือ disciplinary case',prompt:'สรุป case นี้เป็น Facts / Evidence / Risk / Options โดยไม่ตัดสินแทนผู้มีอำนาจ'},
{id:10,group:'Employee Relations & Compliance',icon:'⚖',name:'Labor Compliance QA',thai:'ผู้ตรวจสอบกฎหมายแรงงาน',eq:'HR Compliance / HR Manager',desc:'ตรวจ Policy, ประกาศ, แบบฟอร์ม และ workflow ให้สอดคล้องกับข้อกำหนดที่องค์กรใช้',when:'ก่อนประกาศหรือใช้เอกสาร HR ที่มีผลต่อพนักงาน',prompt:'ตรวจร่างเอกสารนี้ในมุม HR compliance ระบุข้อเท็จจริงที่ต้องยืนยันและจุดที่ต้องให้ผู้เชี่ยวชาญอนุมัติ'},
{id:11,group:'Performance, OD & Data',icon:'📈',name:'Performance & KPI Coach',thai:'โค้ชผลงานและ KPI',eq:'Performance Management / HRD',desc:'ช่วยออกแบบ KPI, review evidence และเปลี่ยน feedback เป็น action plan',when:'ตั้ง KPI ประเมินผลงานหรือทำ performance review',prompt:'แปลงเป้าหมายงานนี้เป็น KPI ที่วัดได้ พร้อม evidence และ review cadence'},
{id:12,group:'Performance, OD & Data',icon:'🎓',name:'L&D Specialist',thai:'นักพัฒนาคนและองค์กร',eq:'Learning & Development',desc:'วิเคราะห์ Skill Gap, training roadmap และ post-training measurement',when:'มี skill gap หรือกำลังทำ training plan',prompt:'วิเคราะห์ skill gap จาก JD และผลการทำงาน แล้วสร้าง learning plan 90 วัน'},
{id:13,group:'Performance, OD & Data',icon:'🧩',name:'OD Designer',thai:'นักออกแบบองค์กร',eq:'Organization Development',desc:'ออกแบบ role, RACI, SOP, operating model และ change plan',when:'มีการปรับโครงสร้างหรือ process',prompt:'ออกแบบ RACI และ workflow ใหม่จากปัญหานี้ พร้อมระบุ role ที่ซ้ำซ้อน'},
{id:14,group:'Performance, OD & Data',icon:'📊',name:'HR Data Analyst',thai:'นักวิเคราะห์ข้อมูล HR',eq:'HR Data Analyst / HRIS',desc:'เปลี่ยนข้อมูล HR เป็น insight, dashboard, trend และ early warning',when:'มีข้อมูลแต่ยังไม่รู้ว่าควรตัดสินใจอะไร',prompt:'วิเคราะห์ dataset นี้ หา trend, anomaly และ 5 action ที่ควรทำต่อ โดยแยก fact กับ assumption'},
{id:15,group:'Knowledge & AI Workforce',icon:'📣',name:'HR Communications',thai:'นักสื่อสารองค์กร HR',eq:'HR Communications / Internal Comms',desc:'ร่างประกาศ FAQ manager brief และข้อความที่เข้าใจง่าย',when:'ต้องสื่อสาร policy หรือ change กับพนักงาน',prompt:'เขียนประกาศ HR จากข้อมูลนี้ 2 เวอร์ชัน: พนักงานอ่านง่าย และ Manager brief'},
{id:16,group:'Knowledge & AI Workforce',icon:'🧠',name:'HR Knowledge Curator',thai:'ผู้ดูแลคลังความรู้ HR',eq:'Knowledge Management / HR Operations',desc:'จัดหมวด Policy, SOP, FAQ, case และ lesson learned ให้ค้นหาได้',when:'เอกสาร HR กระจายหลายที่หรือคำตอบไม่เป็นมาตรฐาน',prompt:'จัดข้อมูลชุดนี้เป็น Knowledge Base พร้อม tags, owner, version และ review date'},
{id:17,group:'Knowledge & AI Workforce',icon:'✦',name:'AI Workforce Designer',thai:'นักออกแบบ AI Workforce',eq:'AI Solution Designer',desc:'ถอดงานซ้ำและวิธีคิดของคนเก่งเป็น Agent + workflow + human checkpoints',when:'มีงานซ้ำทุกวันหรือความรู้สำคัญอยู่กับคนเดียว',prompt:'ถอดงานนี้เป็น AI Agent specification พร้อม input, rules, output, test cases และ human approval points'}
];
const groups=['ทั้งหมด',...new Set(agents.map(a=>a.group))];let activeGroup='ทั้งหมด';
const grid=document.getElementById('agentGrid'),filters=document.getElementById('filters'),search=document.getElementById('agentSearch');
function renderFilters(){filters.innerHTML=groups.map(g=>`<button class="filter ${g===activeGroup?'active':''}" data-group="${g}">${g}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeGroup=b.dataset.group;renderFilters();renderAgents()})}
function renderAgents(){const q=(search.value||'').toLowerCase().trim();const list=agents.filter(a=>(activeGroup==='ทั้งหมด'||a.group===activeGroup)&&(!q||`${a.name} ${a.thai} ${a.desc} ${a.eq} ${a.group}`.toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(a=>`<article class="agent-card" data-id="${a.id}"><div class="agent-top"><span class="agent-num">#${String(a.id).padStart(2,'0')}</span><span class="ready">AI READY</span></div><div class="agent-icon">${a.icon}</div><h3>${a.name}</h3><div class="en">${a.thai}</div><p>${a.desc}</p><div class="agent-foot"><span>${a.group}</span><span>View →</span></div></article>`).join(''):`<div class="callout" style="grid-column:1/-1">ไม่พบ Agent จากคำค้นนี้ ลองค้นคำว่า payroll, attendance, compliance หรือ AI</div>`;document.querySelectorAll('.agent-card').forEach(c=>c.onclick=()=>openAgent(+c.dataset.id))}
search.addEventListener('input',renderAgents);renderFilters();renderAgents();
const dialog=document.getElementById('agentDialog');
function openAgent(id){const a=agents.find(x=>x.id===id);document.getElementById('dialogTitle').textContent=a.name;document.getElementById('dialogBody').innerHTML=`<div class="dialog-en">${a.thai} · ${a.eq}</div><div class="dialog-section"><b>Mission / เก่งเรื่อง</b><p>${a.desc}</p></div><div class="dialog-section"><b>ควรเรียกเมื่อ</b><p>${a.when}</p></div><div class="dialog-section"><b>Prompt ตัวอย่าง</b><pre>${a.prompt}</pre></div><div class="dialog-section"><b>Human approval</b><p>AI วิเคราะห์และร่างผลลัพธ์ แต่ไม่อนุมัติการลงโทษ การเปลี่ยนสิทธิ การจ่ายเงิน หรือการตัดสินใจที่มีผลทางกฎหมายแทนมนุษย์</p></div>`;dialog.showModal()}
document.getElementById('closeDialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
const full=[100,75,45,35,35,45,60,40,55,60,55,60,75,65,40,45,100];document.getElementById('fullCostTable').innerHTML=agents.map((a,i)=>`<tr><td>${a.id}</td><td><b>${a.name}</b><br><span style="color:#8791a0">${a.thai}</span></td><td>${a.eq}</td><td>฿${full[i].toLocaleString()}k</td></tr>`).join('');
const sme=[['HR Manager / HRBP','Strategy · Workforce · ER · OD','฿100k'],['HR Operations Executive','Attendance · Onboarding · Comms','฿50k'],['TA & People Specialist','Recruitment · Onboarding · L&D','฿40k'],['Payroll & C&B Specialist','Payroll · Benefits · Compensation','฿55k'],['HR Data / HRIS Specialist','Data · Knowledge · AI projects','฿60k']];document.getElementById('smeRoles').innerHTML=sme.map(r=>`<div><b>${r[0]}</b><span>${r[1]} · ${r[2]}/เดือน</span></div>`).join('');
const sections=[...document.querySelectorAll('section[id]')];const navs=[...document.querySelectorAll('.nav-item')];const current=document.getElementById('currentSection');const names={dashboard:'Dashboard',team:'AI Specialists', 'first-three':'3 คนที่ควรใช้ก่อน','full-cost':'ต้นทุนทีมเต็ม','sme-cost':'ต้นทุนแบบ SME',agency:'เทียบกับเอเจนซี','extra-cost':'ต้นทุนเพิ่มเติม',workflows:'Workflows',governance:'AI ทำงาน · คุณตัดสินใจ'};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){navs.forEach(n=>n.classList.toggle('active',n.dataset.nav===e.target.id));current.textContent=names[e.target.id]||'Playbook'}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>observer.observe(s));
document.getElementById('searchFocus').onclick=()=>{document.querySelector('#team').scrollIntoView();setTimeout(()=>search.focus(),300)};document.getElementById('connectBtn').onclick=()=>showToast('Connect System: โครงสร้างพร้อมต่อ Feishu / HRIS ใน Phase ถัดไป');
function showToast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
const sidebar=document.getElementById('sidebar');document.getElementById('mobileMenu').onclick=()=>sidebar.classList.toggle('open');navs.forEach(n=>n.addEventListener('click',()=>sidebar.classList.remove('open')));
