const agents=[
{id:1,group:'Strategy & Workforce',icon:'🧭',name:'AI HR Strategist',thai:'นักกลยุทธ์ทรัพยากรบุคคล',market:'HR Business Partner / Human Resources Manager',bench:'60,000–90,000 บาท / 100,000–180,000 บาท',exp:'5–7 / มากกว่า 7 ปี',desc:'เชื่อมกลยุทธ์ธุรกิจกับ People Strategy, HR Roadmap และลำดับความสำคัญของงาน HR',pain:['HR ไม่มี roadmap','ธุรกิจกำลังเปลี่ยนแปลง','ผู้บริหารต้องการ HR ที่เชื่อมกับธุรกิจ'],prompt:'วิเคราะห์เป้าหมายธุรกิจและจัดทำ HR Roadmap 90 วัน พร้อม priorities, owner, KPI และความเสี่ยง'},
{id:2,group:'Strategy & Workforce',icon:'📐',name:'AI Workforce Planner',thai:'นักวางแผนอัตรากำลัง',market:'HR Business Partner / HR Generalist / HR Specialist',bench:'40,000–60,000 บาท',exp:'5–7 ปี',desc:'วิเคราะห์ Headcount, workload, productivity, shift และ manpower budget',pain:['คนไม่พอกับงาน','Overtime สูง','ต้องวางแผนอัตรากำลัง'],prompt:'วิเคราะห์ workload และ capacity แล้วเสนอ manpower plan พร้อมสมมติฐาน'},
{id:3,group:'Employee Lifecycle',icon:'🎯',name:'AI Talent Acquisition Specialist',thai:'นักสรรหาและคัดเลือก',market:'HR Generalist / HR Specialist',bench:'30,000–50,000 บาท',exp:'3–5 ปี',desc:'แตก JD, sourcing strategy, screening rubric, interview guide และ candidate communication',pain:['หาคนยาก','ผู้สมัครเยอะคัดไม่ทัน','JD ไม่ชัด'],prompt:'สร้าง sourcing plan และ screening rubric จาก JD นี้ พร้อมคำถามสัมภาษณ์'},
{id:4,group:'Employee Lifecycle',icon:'🚀',name:'AI Onboarding Specialist',thai:'ผู้ช่วย Onboarding และ Probation',market:'Human Resources Executive / Officer / Staff',bench:'25,000–35,000 บาท',exp:'0–3 ปี',desc:'สร้าง onboarding checklist, 30-60-90 day plan, probation tracking และ handover',pain:['พนักงานใหม่หลุดงาน','Onboarding ไม่เป็นระบบ','ติดตามทดลองงานไม่ทัน'],prompt:'สร้าง onboarding plan 30-60-90 วัน พร้อม owner และ deadline'},
{id:5,group:'Employee Lifecycle',icon:'⏱',name:'AI Attendance Analyst',thai:'นักวิเคราะห์เวลาทำงาน',market:'HR / Administrative Officer',bench:'20,000–30,000 บาท',exp:'0–3 ปี',desc:'วิเคราะห์เวลาเข้าออก ลา มาสาย ขาดงาน OT และ anomaly เพื่อส่งต่อ HR',pain:['มาสาย/ขาดงานสูง','OT สูง','ข้อมูลเวลาผิดปกติ'],prompt:'วิเคราะห์ attendance dataset หา anomaly, trend และรายการที่ต้องตรวจเพิ่ม'},
{id:6,group:'Employee Lifecycle',icon:'💰',name:'AI Payroll Specialist',thai:'ผู้ช่วย Payroll',market:'HR - Compensation & Benefit',bench:'25,000–35,000 บาท',exp:'0–3 ปี',desc:'ตรวจ input เงินเดือน ลา OT หัก และ validation rules ก่อนส่งอนุมัติ',pain:['ปิด Payroll ช้า','Payroll ผิด','ตรวจข้อมูลหลายไฟล์'],prompt:'ตรวจ payroll input ตาม checklist และแยกรายการ exception ที่ต้องยืนยัน'},
{id:7,group:'Employee Lifecycle',icon:'⚖',name:'AI Compensation Analyst',thai:'นักวิเคราะห์ค่าตอบแทน',market:'Compensation and Benefit Manager / HR - C&B',bench:'70,000–100,000 บาท / 25,000–35,000 บาท',exp:'5–7 / 0–3 ปี',desc:'วิเคราะห์ salary structure, internal equity, incentive และ market benchmark',pain:['โครงสร้างเงินเดือนไม่ชัด','ปรับเงินเดือนยาก','ต้องวิเคราะห์ความเป็นธรรม'],prompt:'วิเคราะห์ salary structure และ internal equity โดยแยก fact, assumption และ recommendation'},
{id:8,group:'Employee Lifecycle',icon:'🎁',name:'AI Benefits Specialist',thai:'ผู้ช่วยสวัสดิการและสิทธิประโยชน์',market:'HR Generalist / HR Specialist',bench:'30,000–50,000 บาท',exp:'3–5 ปี',desc:'จัด FAQ สิทธิ สวัสดิการ เงื่อนไขการเบิก และ case routing',pain:['พนักงานถามสิทธิเยอะ','HR ตอบซ้ำ','สวัสดิการซับซ้อน'],prompt:'แปลง policy สวัสดิการเป็น FAQ พร้อมเงื่อนไขและกรณีส่งต่อ HR'},
{id:9,group:'Employee Relations & Compliance',icon:'🤝',name:'AI Employee Relations Advisor',thai:'ที่ปรึกษาพนักงานสัมพันธ์',market:'HRM Manager',bench:'50,000–70,000 บาท / 70,000–120,000 บาท',exp:'5–7 / มากกว่า 7 ปี',desc:'จัดโครงสร้าง complaint, conflict, evidence และทางเลือกในการจัดการ case',pain:['ข้อร้องเรียนเยอะ','Conflict ในทีม','Case วินัยซับซ้อน'],prompt:'สรุป case เป็น Facts / Evidence / Risk / Options โดยไม่ตัดสินแทนผู้มีอำนาจ'},
{id:10,group:'Employee Relations & Compliance',icon:'⚖',name:'AI Labor Compliance QA',thai:'ผู้ตรวจสอบ HR Compliance',market:'Human Resources Manager / AVP - Human Resources',bench:'60,000–90,000 บาท / 100,000–180,000 บาท',exp:'5–7 / มากกว่า 7 ปี',desc:'ตรวจ policy, ประกาศ, แบบฟอร์ม และ workflow พร้อมระบุประเด็นที่ต้องยืนยัน',pain:['กลัวเอกสารผิดกฎหมาย','เปลี่ยน policy','ต้องตรวจเอกสาร HR จำนวนมาก'],prompt:'ตรวจร่างเอกสาร HR ระบุ evidence ที่ต้องยืนยันและจุดที่ต้องให้ผู้เชี่ยวชาญอนุมัติ'},
{id:11,group:'Performance, OD & Data',icon:'📈',name:'AI Performance & KPI Coach',thai:'โค้ช Performance และ KPI',market:'HRD Manager / HROD Manager',bench:'60,000–80,000 บาท / 60,000–100,000 บาท',exp:'5–7 ปี',desc:'ออกแบบ KPI, review evidence, feedback และ performance action plan',pain:['KPI วัดไม่ได้','ประเมินผลงานไม่มาตรฐาน','Manager เขียน feedback ยาก'],prompt:'แปลงเป้าหมายเป็น KPI ที่วัดได้ พร้อม evidence และ review cadence'},
{id:12,group:'Performance, OD & Data',icon:'🎓',name:'AI Learning & Development Specialist',thai:'นักพัฒนาคนและการเรียนรู้',market:'HRD Manager',bench:'60,000–80,000 บาท / 80,000–150,000 บาท',exp:'5–7 / มากกว่า 7 ปี',desc:'วิเคราะห์ skill gap, learning roadmap, training content และ post-training measurement',pain:['Skill gap สูง','Training ไม่ตรงปัญหา','วัดผลอบรมไม่ได้'],prompt:'วิเคราะห์ skill gap และสร้าง learning plan 90 วันพร้อมตัวชี้วัด'},
{id:13,group:'Performance, OD & Data',icon:'🧩',name:'AI Organization Development Designer',thai:'นักออกแบบองค์กรและกระบวนการ',market:'HROD Manager',bench:'60,000–100,000 บาท / 80,000–150,000 บาท',exp:'5–7 / มากกว่า 7 ปี',desc:'ออกแบบ role, RACI, SOP, operating model และ change plan',pain:['โครงสร้างซ้ำซ้อน','Role ไม่ชัด','Process HR ไม่ลื่นไหล'],prompt:'ออกแบบ RACI และ workflow จากปัญหานี้ พร้อมระบุ role ที่ซ้ำซ้อน'},
{id:14,group:'Performance, OD & Data',icon:'📊',name:'AI HR Data & People Analytics',thai:'นักวิเคราะห์ข้อมูลบุคลากร',market:'HRIS / HR Business Partner',bench:'50,000–80,000 บาท / 60,000–80,000 บาท',exp:'5–7 ปี',desc:'เปลี่ยนข้อมูล HR เป็น insight, dashboard, trend และ early warning',pain:['มีข้อมูลแต่ใช้ตัดสินใจไม่ได้','Turnover สูง','ต้องทำ Dashboard'],prompt:'วิเคราะห์ dataset หา trend, anomaly และ action โดยแยก fact กับ assumption'},
{id:15,group:'Knowledge & AI Workforce',icon:'📣',name:'AI HR Communications Specialist',thai:'นักสื่อสาร HR',market:'Human Resources Executive / Officer / Staff',bench:'25,000–35,000 บาท / 35,000–50,000 บาท',exp:'0–3 / 3–5 ปี',desc:'ร่างประกาศ FAQ manager brief และข้อความเปลี่ยนแปลงที่เข้าใจง่าย',pain:['ประกาศ HR คนไม่เข้าใจ','ต้องสื่อสาร policy ใหม่','Manager สื่อสารไม่ตรงกัน'],prompt:'เขียนประกาศ HR และ manager brief จาก policy นี้'},
{id:16,group:'Knowledge & AI Workforce',icon:'🧠',name:'AI HR Knowledge Manager',thai:'ผู้ดูแลคลังความรู้ HR',market:'Human Resources Executive / Officer / Staff',bench:'25,000–35,000 บาท / 35,000–50,000 บาท',exp:'0–3 / 3–5 ปี',desc:'จัด Policy, SOP, FAQ, case และ lesson learned ให้ค้นหาและใช้ซ้ำได้',pain:['เอกสารกระจาย','ตอบ HR ไม่เหมือนกัน','ความรู้ติดอยู่กับคน'],prompt:'จัดข้อมูลเป็น knowledge base พร้อม tags, owner, version และ review date'},
{id:17,group:'Knowledge & AI Workforce',icon:'✦',name:'AI Workforce Designer',thai:'นักออกแบบ AI Workforce',market:'HRIS / HROD / HR Business Partner',bench:'50,000–80,000 บาท / 60,000–100,000 บาท',exp:'5–7 ปี',desc:'ถอดงาน HR ที่ทำซ้ำเป็น Agent, workflow, rules, test cases และ human checkpoints',pain:['งาน HR ซ้ำทุกวัน','ทีมเล็กแต่งานเยอะ','อยากสร้าง HR AI ภายใน'],prompt:'ถอดงานนี้เป็น AI Agent specification พร้อม input, rules, output, test cases และ approval points'}
];
const pains=[
['🧮','งาน HR เยอะ แต่ทีมเล็ก','ต้องการเพิ่ม capacity โดยไม่เพิ่มคนทันที',['AI HR Data & People Analytics','AI Workforce Designer','AI HR Knowledge Manager']],
['⏱','Payroll / Attendance ใช้เวลามาก','ข้อมูลหลายระบบ ตรวจซ้ำ และมี exception เยอะ',['AI Attendance Analyst','AI Payroll Specialist','AI HR Data & People Analytics']],
['🎯','สรรหาคนไม่ทันธุรกิจ','เปิดงานบ่อย ผู้สมัครเยอะ หรือหาคนยาก',['AI Workforce Planner','AI Talent Acquisition Specialist','AI Onboarding Specialist']],
['⚖','กังวลความเสี่ยงแรงงาน','Policy / ประกาศ / case มีผลต่อคนและกฎหมาย',['AI Labor Compliance QA','AI Employee Relations Advisor','AI HR Communications Specialist']],
['📈','Performance / Skill Gap ไม่ชัด','KPI ไม่มาตรฐานและพัฒนาไม่ตรงจุด',['AI Performance & KPI Coach','AI Learning & Development Specialist','AI HR Data & People Analytics']],
['🧩','องค์กรกำลังปรับโครงสร้าง','Role, RACI และ process ไม่ชัด',['AI HR Strategist','AI Organization Development Designer','AI Workforce Planner']],
['📚','ความรู้ HR กระจาย','เอกสารอยู่หลายที่และคำตอบไม่เป็นมาตรฐาน',['AI HR Knowledge Manager','AI HR Communications Specialist','AI Labor Compliance QA']],
['🤖','ต้องการสร้าง HR AI ระยะยาว','ต้องการเปลี่ยนงานซ้ำและความรู้เป็นระบบ AI',['AI Workforce Designer','AI HR Data & People Analytics','AI HR Knowledge Manager']]
];
const packages=[
['HR Core Automation','สำหรับทีม HR ที่ต้องการลดงานประจำ','AI HR Data & People Analytics','AI Attendance Analyst','AI Payroll Specialist','AI HR Knowledge Manager'],
['Recruitment & Workforce','สำหรับธุรกิจที่กำลังขยายทีม','AI Workforce Planner','AI Talent Acquisition Specialist','AI Onboarding Specialist','AI HR Data & People Analytics'],
['HR Risk & ER','สำหรับองค์กรที่ต้องการยกระดับความเสี่ยงและเอกสาร','AI Labor Compliance QA','AI Employee Relations Advisor','AI HR Communications Specialist'],
['People Development','สำหรับ Performance, KPI และการพัฒนาคน','AI Performance & KPI Coach','AI Learning & Development Specialist','AI Organization Development Designer'],
['AI HR Transformation','สำหรับองค์กรที่ต้องการสร้าง HR AI Operating Model','AI HR Strategist','AI Workforce Designer','AI HR Knowledge Manager','AI HR Data & People Analytics']
];
const workflows=[['Attendance anomaly','Attendance → Data Analytics → ER/Compliance → Human decision'],['Payroll','Attendance + Leave + OT → Payroll → Validation → Approval → HRIS/Feishu'],['Recruitment','Manpower Plan → TA → Screening → Interview → Hiring Manager'],['Policy change','Business request → HR Strategist → Labor QA → Human approval → Communication'],['Learning','Performance/Skill Data → L&D → Learning Plan → Manager → Measurement']];
const groups=['ทั้งหมด',...new Set(agents.map(a=>a.group))];let activeGroup='ทั้งหมด';
const $=id=>document.getElementById(id);const grid=$('agentGrid'),filters=$('filters'),search=$('agentSearch');
function renderFilters(){filters.innerHTML=groups.map(g=>`<button class="filter ${g===activeGroup?'active':''}" data-group="${g}">${g}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeGroup=b.dataset.group;renderFilters();renderAgents()})}
function renderAgents(){const q=(search.value||'').toLowerCase().trim();const list=agents.filter(a=>(activeGroup==='ทั้งหมด'||a.group===activeGroup)&&(!q||`${a.name} ${a.thai} ${a.desc} ${a.market} ${a.pain.join(' ')}`.toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(a=>`<article class="agent-card" data-id="${a.id}"><div class="agent-top"><span class="agent-num">#${String(a.id).padStart(2,'0')}</span><span class="ready">SELECTABLE</span></div><div class="agent-icon">${a.icon}</div><h3>${a.name}</h3><div class="en">${a.thai}</div><p>${a.desc}</p><div class="agent-foot"><span>${a.group}</span><span>View →</span></div></article>`).join(''):`<div class="callout" style="grid-column:1/-1">ไม่พบ Agent จากคำค้นนี้ ลองค้น payroll, attendance, recruitment, compliance หรือ data</div>`;document.querySelectorAll('.agent-card').forEach(c=>c.onclick=()=>openAgent(+c.dataset.id))}
function openAgent(id){const a=agents.find(x=>x.id===id);$('dialogTitle').textContent=a.name;$('dialogBody').innerHTML=`<div class="dialog-en">${a.thai} · ${a.market}</div><div class="dialog-section"><b>Mission</b><p>${a.desc}</p></div><div class="dialog-section"><b>Pain ที่เหมาะกับ Agent นี้</b><p>${a.pain.join(' · ')}</p></div><div class="dialog-section"><b>Market benchmark (มนุษย์)</b><p>${a.bench} · ${a.exp}</p></div><div class="dialog-section"><b>ตัวอย่าง Prompt</b><pre>${a.prompt}</pre></div><div class="dialog-section"><b>Human approval</b><p>AI วิเคราะห์/ร่าง/ตรวจได้ แต่ไม่อนุมัติการลงโทษ การเลิกจ้าง การเปลี่ยนสภาพการจ้าง การจ่ายเงิน หรือสิทธิสำคัญแทนมนุษย์</p></div>`;$('agentDialog').showModal()}
$('closeDialog').onclick=()=>$('agentDialog').close();$('agentDialog').addEventListener('click',e=>{if(e.target===$('agentDialog'))$('agentDialog').close()});search.addEventListener('input',renderAgents);renderFilters();renderAgents();
$('painGrid').innerHTML=pains.map((p,i)=>`<article class="priority-card ${i===0?'featured':''}"><span class="rank">${String(i+1).padStart(2,'0')}</span><div class="priority-icon">${p[0]}</div><h3>${p[1]}</h3><p>${p[2]}</p><b>${p[3].join(' · ')}</b></article>`).join('');
const money=n=>`${Math.round(n).toLocaleString('th-TH')} บาท`;
function benchmarkAverage(bench){
  const nums=(bench.match(/[0-9][0-9,]*/g)||[]).map(x=>Number(x.replace(/,/g,'')));
  let mids=[]; for(let i=0;i+1<nums.length;i+=2) mids.push((nums[i]+nums[i+1])/2);
  return mids.length ? mids.reduce((a,b)=>a+b,0)/mids.length : 0;
}
agents.forEach(a=>a.benchmarkAverage=benchmarkAverage(a.bench));
let selectedAgents=new Set();
function renderChooser(){
  const byGroup={}; agents.forEach(a=>(byGroup[a.group]??=[]).push(a));
  $('chooserOptions').innerHTML=Object.entries(byGroup).map(([group,list])=>`<div class="chooser-group"><h4>${group}</h4>${list.map(a=>`<label class="chooser-option"><input type="checkbox" data-agent-id="${a.id}" ${selectedAgents.has(a.id)?'checked':''}><span class="chooser-check"></span><span class="chooser-main"><b>${a.name}</b><small>${a.thai}</small></span><span class="chooser-benchmark">${money(a.benchmarkAverage)}<small>/ เดือน โดยเฉลี่ย</small></span></label>`).join('')}</div>`).join('');
  document.querySelectorAll('#chooserOptions input').forEach(input=>input.onchange=()=>{const id=+input.dataset.agentId;if(input.checked)selectedAgents.add(id);else selectedAgents.delete(id);updateChooserSummary();});
}
function updateChooserSummary(){
  const chosen=agents.filter(a=>selectedAgents.has(a.id));
  const monthly=chosen.reduce((sum,a)=>sum+a.benchmarkAverage,0), yearly=monthly*12;
  $('selectedCount').textContent=`${chosen.length} Agent`;
  $('monthlyBenchmark').textContent=money(monthly);
  $('yearlyBenchmark').textContent=money(yearly);
  $('builderSummary').innerHTML=chosen.length?`<span>ทีมที่เลือก</span><strong>${money(monthly)}</strong><small>/ เดือน · ${money(yearly)} / ปี</small>`:`<span>ยังไม่ได้เลือก Agent</span><strong>0 บาท</strong><small>Benchmark ต่อเดือน</small>`;
  const fee=Number($('serviceFee').value||0);
  if(fee>0&&monthly>0){
    const saving=monthly-fee;
    $('monthlySaving').textContent=money(saving);
    $('yearlySaving').textContent=money(saving*12);
    $('costRatio').textContent=`${((fee/monthly)*100).toFixed(1)}%`;
  }else{$('monthlySaving').textContent='—';$('yearlySaving').textContent='—';$('costRatio').textContent='—';}
}
$('packageGrid').innerHTML=packages.map(p=>`<article class="priority-card"><div class="priority-icon">✦</div><h3>${p[0]}</h3><p>${p[1]}</p><b>${p.slice(2).join(' · ')}</b><button class="package-select" data-package="${p[0]}">เลือกชุดนี้</button></article>`).join('');
$('openChooser').onclick=()=>{$('chooserDialog').showModal();renderChooser();updateChooserSummary()};
$('closeChooser').onclick=()=>$('chooserDialog').close();
$('chooserDialog').addEventListener('click',e=>{if(e.target===$('chooserDialog'))$('chooserDialog').close()});
$('serviceFee').addEventListener('input',updateChooserSummary);
document.querySelectorAll('.package-select').forEach(btn=>btn.onclick=()=>{const pack=packages.find(p=>p[0]===btn.dataset.package);selectedAgents=new Set(pack.slice(2).map(name=>agents.find(a=>a.name===name)?.id).filter(Boolean));$('chooserDialog').showModal();renderChooser();updateChooserSummary();});
$('confirmSelection').onclick=()=>{$('chooserDialog').close();document.querySelector('#packages').scrollIntoView({behavior:'smooth'});showToast(`เลือก ${selectedAgents.size} Agent แล้ว`)};
$('workflowGrid').innerHTML=workflows.map(w=>`<article><span>${w[0]}</span><p>${w[1]}</p></article>`).join('');
$('benchmarkTable').innerHTML=agents.map(a=>`<tr><td><b>${a.name}</b><br><span style="color:#8791a0">${a.thai}</span></td><td>${a.market}</td><td>${a.bench}</td><td>${a.exp}</td></tr>`).join('');
const sections=[...document.querySelectorAll('section[id]')],navs=[...document.querySelectorAll('.nav-item')];const names={dashboard:'ภาพรวม','pain-points':'เลือกจาก Pain Point',team:'AI HR Specialists',packages:'ชุดบริการ',benchmark:'Market Benchmark',workflows:'Workflows',governance:'AI ทำงาน · คุณตัดสินใจ'};const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){navs.forEach(n=>n.classList.toggle('active',n.dataset.nav===e.target.id));$('currentSection').textContent=names[e.target.id]||'Playbook'}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>observer.observe(s));
$('searchFocus').onclick=()=>{document.querySelector('#team').scrollIntoView();setTimeout(()=>search.focus(),300)};$('connectBtn').onclick=()=>{document.querySelector('#pain-points').scrollIntoView({behavior:'smooth'});showToast('เริ่มจาก Pain Point แล้วเลือก Agent ที่ต้องการ')};
$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');function showToast(t){const el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
